config/routes.rb
Rails.application.routes.draw do
	root to: "cars#index"

  resources :cars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:marca, :modelo, :ano, :cor)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for(car) do |f| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :marca %>
    <%= f.text_field :marca %>
  </div>

  <div class="field">
    <%= f.label :modelo %>
    <%= f.text_field :modelo %>
  </div>

  <div class="field">
    <%= f.label :ano %>
    <%= f.number_field :ano %>
  </div>

  <div class="field">
    <%= f.label :cor %>
    <%= f.text_field :cor %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>

<%= link_to 'New Car', new_car_path, class: "mdl-button mdl-button--primary mdl-button--raised container-element" %>

<div class="form-container">
  <input type="text" ng-model="new_car.marca" placeholder="Marca">
  <input type="text" ng-model="new_car.modelo" placeholder="Modelo">
  <input type="text" ng-model="new_car.ano" placeholder="Ano">
  <input type="text" ng-model="new_car.cor" placeholder="Cor">

  <button class="mdl-button mdl-button--raised mdl-button--primary" ng-click="add_car(new_car)">
    Add new car
  </button>
</div>

<h3>Angular table:</h3>
<table class="mdl-data-table">
  <thead>
    <tr>
      <th class="mdl-data-table--cell-non-numeric">Marca</th>
      <th>Modelo</th>
      <th>Ano</th>
      <th>Cor</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr ng-repeat="car in cars">
      <td class="mdl-data-table--cell-non-numeric">
        <span ng-show="!car.editable">{{car.marca}}</span>
        <input type="text" ng-show="car.editable" ng-model="car.marca">
      </td>
      <td>
        <span ng-show="!car.editable">{{car.modelo}}</span>
        <input type="text" ng-show="car.editable" ng-model="car.modelo">
      </td>
      <td>
        <span ng-show="!car.editable">{{car.ano}}</span>
        <input type="text" ng-show="car.editable" ng-model="car.ano">
      </td>
      <td>
        <span ng-show="!car.editable">{{car.cor}}</span>
        <input type="text" ng-show="car.editable" ng-model="car.cor">
      </td>
      <td ng-click="edit_car(car)">
        <a href="" ng-show="!car.editable" ng-click="edit_car(car)" ng-model="car.editable">Editar</a>
        <a href="" ng-show="car.editable" ng-click="update_car(car)">Salvar</a>
      </td>
      <td ng-click="delete_car(car)"><a href="">Apagar</a></td>
    </tr>
  </tbody>
</table>

<br><br><br>

<h3>Rails table:</h3>
<table class="mdl-data-table">
  <thead>
    <tr>
      <th class="mdl-data-table--cell-non-numeric">Marca</th>
      <th>Modelo</th>
      <th>Ano</th>
      <th>Cor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td class="mdl-data-table--cell-non-numeric"><%= car.marca %></td>
        <td><%= car.modelo %></td>
        <td><%= car.ano %></td>
        <td><%= car.cor %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Marca:</strong>
  <%= @car.marca %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @car.modelo %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @car.ano %>
</p>

<p>
  <strong>Cor:</strong>
  <%= @car.cor %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="Concessionaria">
  <head>
    <title>AngularConcessionariaRails</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- MDL -->
		<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
		<link rel="stylesheet" href="https://code.getmdl.io/1.2.1/material.indigo-pink.min.css">
		<script defer src="https://code.getmdl.io/1.2.1/material.min.js"></script>

		<!-- ANGULAR -->
		<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.min.js"></script>	
		<script>
			angular.module("Concessionaria", []);
			angular.module("Concessionaria").controller("ConcessionariaCtrl", function($scope, $http){

				$scope.app = "Angular - Concessionária";

				var load_cars = function(){
					$http.get("http://localhost:3000/cars.json").success(function(cars_data){
						$scope.cars = cars_data;
						console.log("Deu bom!");
					});	
				}

				$scope.add_car = function(new_car){
					$http.post("http://localhost:3000/cars.json", new_car).success(function(new_car){
						delete $scope.new_car;
						load_cars();
					});
				}

				$scope.delete_car = function(car){
					$http.delete(car.url, car).success(function(car){
						load_cars();
					});
				}

				$scope.edit_car = function(car){
					car.editable = true;
				}

				$scope.update_car = function(car){
					$http.put(car.url, car).success(function(car){
						car.editable = false;
						load_cars();
					});
				}

				load_cars();

			});
		</script>
  </head>

  <body class="mdl-layout mdl-layout--fixed-header" ng-controller="ConcessionariaCtrl">
  	<header class="mdl-layout__header">
  		<div class="mdl-layout__header-row">
  			<span class="mdl-title">{{app}}</span>
  		</div>
  	</header>

  	<main class="mdl-layout__content">
  		<%= yield %>
  	</main>
    
  </body>
</html>